# Generated by Django 5.1.6 on 2025-03-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус экземпляра книги', max_length=40, verbose_name=' название курса')),
            ],
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите день недели', max_length=40, verbose_name=' день недели')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(help_text='Введите Дату рождения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Выберите жанр для книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='жанр книги'),
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя лектора', max_length=40, verbose_name='имя лектора')),
                ('surname', models.CharField(help_text='Введите фамилия лектора', max_length=40, verbose_name='фамилия лектора')),
                ('course', models.ManyToManyField(help_text='Введите курс', to='catalog.course', verbose_name='курс')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя студента', max_length=40, verbose_name='имя студента')),
                ('surname', models.CharField(help_text='Введите фамилия студента', max_length=40, verbose_name='фамилия студента')),
                ('age', models.IntegerField(help_text='введите возраст студента', verbose_name='возраст студента')),
                ('curses', models.ManyToManyField(help_text='выберите курсы студента', to='catalog.course', verbose_name='курсы студента')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя урока', max_length=40, verbose_name='имя урока')),
                ('lenght', models.IntegerField(help_text='введите длительность урока', verbose_name='длительность урока')),
                ('day', models.ForeignKey(help_text='выберите день проведения', on_delete=django.db.models.deletion.CASCADE, to='catalog.day', verbose_name='день проведения')),
                ('lector', models.ForeignKey(help_text='выберите лектора', on_delete=django.db.models.deletion.CASCADE, to='catalog.lector', verbose_name='лектора')),
                ('students', models.ManyToManyField(help_text='выберите студентов', to='catalog.student', verbose_name='студенты')),
            ],
        ),
    ]
