# Generated by Django 5.1.6 on 2025-03-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Выберите язык книги',
                                    null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='catalog.language', verbose_name='язык книги'),
        ),
    ]
