# Generated by Django 5.1.6 on 2025-05-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_course_day_alter_author_date_of_birth_and_more'),
        ('catalog', '0003_book_language'),
    ]

    operations = [
    ]
